### ISSUE TITLE
Inquiries from a Beginner

### ISSUE THREAD

**Issue by Hades-Levi** [yuanzhi-zhu/DiffPIR#16]
Hello, I am a beginner and English is not my native language, please pardon any incorrect descriptions. I have a few questions. Firstly, as far as I know, Google's SR3 super-resolution model also applies diffusion models to image restoration. I would like to know the differences between this model and SR3, as well as the overall architecture. What are the core innovations? Secondly, what efforts do I need to make if I want to input 512*512 images? Thank you very much for your answers!

**Comment by yuanzhi-zhu** [comment]
1. Our approach utilizes pre-trained diffusion models as generative denoiser prior, while SR3 is a model trained directly for SR. In other words, SR3 is a **conditional** diffusion model with the low-resolution image as condition input.
To know more details about our approach, motivation and method, please have a look at this [slide](https://yuanzhi-zhu.github.io/documents/slides/diffusion_models_for_pnp_IR.pdf).
2. In order to _output_ 512\*512 images, you just need to employ unconditional diffusion models that are trained on images with size 512\*512.
